// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: categories.proto

package business_entity_categories

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CategoriesData is the root message for the categories package.
type CategoriesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories    []*BusinessCategory         `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	SubCategories map[string]*SubCategoryList `protobuf:"bytes,2,rep,name=sub_categories,proto3" json:"sub_categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CategoriesData) Reset() {
	*x = CategoriesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesData) ProtoMessage() {}

func (x *CategoriesData) ProtoReflect() protoreflect.Message {
	mi := &file_categories_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesData.ProtoReflect.Descriptor instead.
func (*CategoriesData) Descriptor() ([]byte, []int) {
	return file_categories_proto_rawDescGZIP(), []int{0}
}

func (x *CategoriesData) GetCategories() []*BusinessCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CategoriesData) GetSubCategories() map[string]*SubCategoryList {
	if x != nil {
		return x.SubCategories
	}
	return nil
}

// BusinessCategory represents a top-level or sub-level business category.
type BusinessCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *BusinessCategory) Reset() {
	*x = BusinessCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessCategory) ProtoMessage() {}

func (x *BusinessCategory) ProtoReflect() protoreflect.Message {
	mi := &file_categories_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessCategory.ProtoReflect.Descriptor instead.
func (*BusinessCategory) Descriptor() ([]byte, []int) {
	return file_categories_proto_rawDescGZIP(), []int{1}
}

func (x *BusinessCategory) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BusinessCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BusinessCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SubCategoryList wraps repeated BusinessCategory as a map value (proto3 maps
// cannot hold repeated values directly).
type SubCategoryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*BusinessCategory `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SubCategoryList) Reset() {
	*x = SubCategoryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubCategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryList) ProtoMessage() {}

func (x *SubCategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_categories_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryList.ProtoReflect.Descriptor instead.
func (*SubCategoryList) Descriptor() ([]byte, []int) {
	return file_categories_proto_rawDescGZIP(), []int{2}
}

func (x *SubCategoryList) GetItems() []*BusinessCategory {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_categories_proto protoreflect.FileDescriptor

var file_categories_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x93, 0x02, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x5a, 0x0a, 0x0e, 0x73, 0x75, 0x62,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x32, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x62, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x53,
	0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a, 0x10, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x42, 0x63, 0x5a, 0x61, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x61, 0x7a, 0x6f, 0x72, 0x70, 0x61, 0x79, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x69,
	0x66, 0x79, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x69, 0x66, 0x79, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x67, 0x6f, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x3b, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_categories_proto_rawDescOnce sync.Once
	file_categories_proto_rawDescData = file_categories_proto_rawDesc
)

func file_categories_proto_rawDescGZIP() []byte {
	file_categories_proto_rawDescOnce.Do(func() {
		file_categories_proto_rawDescData = protoimpl.X.CompressGZIP(file_categories_proto_rawDescData)
	})
	return file_categories_proto_rawDescData
}

var file_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_categories_proto_goTypes = []interface{}{
	(*CategoriesData)(nil),   // 0: business_entity.CategoriesData
	(*BusinessCategory)(nil), // 1: business_entity.BusinessCategory
	(*SubCategoryList)(nil),  // 2: business_entity.SubCategoryList
	nil,                      // 3: business_entity.CategoriesData.SubCategoriesEntry
}
var file_categories_proto_depIdxs = []int32{
	1, // 0: business_entity.CategoriesData.categories:type_name -> business_entity.BusinessCategory
	3, // 1: business_entity.CategoriesData.sub_categories:type_name -> business_entity.CategoriesData.SubCategoriesEntry
	1, // 2: business_entity.SubCategoryList.items:type_name -> business_entity.BusinessCategory
	2, // 3: business_entity.CategoriesData.SubCategoriesEntry.value:type_name -> business_entity.SubCategoryList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_categories_proto_init() }
func file_categories_proto_init() {
	if File_categories_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_categories_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categories_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categories_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubCategoryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_categories_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_categories_proto_goTypes,
		DependencyIndexes: file_categories_proto_depIdxs,
		MessageInfos:      file_categories_proto_msgTypes,
	}.Build()
	File_categories_proto = out.File
	file_categories_proto_rawDesc = nil
	file_categories_proto_goTypes = nil
	file_categories_proto_depIdxs = nil
}
