// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity_categories

import (
	"testing"
)

// TestGetCategoriesData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetCategoriesData(t *testing.T) {
	data, err := GetCategoriesData()
	if err != nil {
		t.Fatalf("GetCategoriesData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetCategoriesData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetCategoriesData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetCategoriesData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetCategoriesData()
	if err1 != nil {
		t.Fatalf("First GetCategoriesData() error = %v", err1)
	}

	data2, err2 := GetCategoriesData()
	if err2 != nil {
		t.Fatalf("Second GetCategoriesData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetCategoriesData() should return cached data on subsequent calls")
	}
}

// TestGetCategoriesData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetCategoriesData_NotEmpty(t *testing.T) {
	data, err := GetCategoriesData()
	if err != nil {
		t.Fatalf("GetCategoriesData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
