// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity_categories

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *CategoriesData
	dataOnce sync.Once
	dataErr  error
)

// GetCategoriesData retrieves the data.
func GetCategoriesData() (*CategoriesData, error) {
	dataOnce.Do(func() {
		data = &CategoriesData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
