// Code generated by i18nify go generator. DO NOT EDIT.

package country_metadata

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *CountryMetadataData
	dataOnce sync.Once
	dataErr  error
)

// GetCountryMetadataData retrieves the data.
func GetCountryMetadataData() (*CountryMetadataData, error) {
	dataOnce.Do(func() {
		data = &CountryMetadataData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
