// Code generated by i18nify go generator. DO NOT EDIT.

package country_metadata

import (
	"testing"
)

// TestGetCountryMetadataData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetCountryMetadataData(t *testing.T) {
	data, err := GetCountryMetadataData()
	if err != nil {
		t.Fatalf("GetCountryMetadataData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetCountryMetadataData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetCountryMetadataData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetCountryMetadataData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetCountryMetadataData()
	if err1 != nil {
		t.Fatalf("First GetCountryMetadataData() error = %v", err1)
	}

	data2, err2 := GetCountryMetadataData()
	if err2 != nil {
		t.Fatalf("Second GetCountryMetadataData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetCountryMetadataData() should return cached data on subsequent calls")
	}
}

// TestGetCountryMetadataData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetCountryMetadataData_NotEmpty(t *testing.T) {
	data, err := GetCountryMetadataData()
	if err != nil {
		t.Fatalf("GetCountryMetadataData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
