// Code generated by i18nify go generator. DO NOT EDIT.

package country_metadata

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *CountryMetadataData
	dataOnce sync.Once
	dataErr  error
)

// GetCountryMetadataData retrieves the data.
func GetCountryMetadataData() (*CountryMetadataData, error) {
	dataOnce.Do(func() {
		data = &CountryMetadataData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
