// Code generated by i18nify go generator. DO NOT EDIT.

package datetime

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *DateTimeData
	dataOnce sync.Once
	dataErr  error
)

// GetDateTimeData retrieves the datetime configuration data.
// The JSON is parsed exactly once; subsequent calls return the cached result.
func GetDateTimeData() (*DateTimeData, error) {
	dataOnce.Do(func() {
		data = &DateTimeData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
