// Code generated by i18nify go generator. DO NOT EDIT.

package datetime

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *DateTimeData
	dataOnce sync.Once
	dataErr  error
)

// GetDateTimeData retrieves the data.
func GetDateTimeData() (*DateTimeData, error) {
	dataOnce.Do(func() {
		data = &DateTimeData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
