// Code generated by i18nify go generator. DO NOT EDIT.

package datetime

import (
	_ "embed"
	"fmt"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	dataOnce sync.Once
	data     *DateTimeData
	dataErr  error
)

// GetDateTimeData returns the locale datetime configuration.
func GetDateTimeData() (*DateTimeData, error) {
	dataOnce.Do(func() {
		d := &DateTimeData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		if err := unmarshaler.Unmarshal(dataJSON, d); err != nil {
			dataErr = fmt.Errorf("datetime: failed to parse data.json: %w", err)
			return
		}
		data = d
	})
	return data, dataErr
}
