// Code generated by i18nify go generator. DO NOT EDIT.

package datetime

import (
	"testing"
)

// TestGetDateTimeData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetDateTimeData(t *testing.T) {
	data, err := GetDateTimeData()
	if err != nil {
		t.Fatalf("GetDateTimeData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetDateTimeData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetDateTimeData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetDateTimeData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetDateTimeData()
	if err1 != nil {
		t.Fatalf("First GetDateTimeData() error = %v", err1)
	}

	data2, err2 := GetDateTimeData()
	if err2 != nil {
		t.Fatalf("Second GetDateTimeData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetDateTimeData() should return cached data on subsequent calls")
	}
}

// TestGetDateTimeData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetDateTimeData_NotEmpty(t *testing.T) {
	data, err := GetDateTimeData()
	if err != nil {
		t.Fatalf("GetDateTimeData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
