// Code generated by i18nify go generator. DO NOT EDIT.

package datetime

import (
	"testing"
)

func TestGetDateTimeData(t *testing.T) {
	d, err := GetDateTimeData()
	if err != nil {
		t.Fatalf("GetDateTimeData() error = %v", err)
	}
	if d == nil {
		t.Fatal("GetDateTimeData() returned nil")
	}
}

func TestGetDateTimeData_Idempotent(t *testing.T) {
	d1, err1 := GetDateTimeData()
	if err1 != nil {
		t.Fatalf("first call error: %v", err1)
	}
	d2, err2 := GetDateTimeData()
	if err2 != nil {
		t.Fatalf("second call error: %v", err2)
	}
	if d1 != d2 {
		t.Error("GetDateTimeData() must return the same cached pointer on repeated calls")
	}
}

func TestGetDateTimeData_LocaleDateOrders(t *testing.T) {
	d, err := GetDateTimeData()
	if err != nil {
		t.Fatalf("GetDateTimeData() error = %v", err)
	}
	cases := map[string]string{
		"en-US": "MDY",
		"en-CA": "MDY",
		"ja":    "YMD",
		"ko":    "YMD",
		"zh":    "YMD",
		"hu":    "YMD",
	}
	for locale, want := range cases {
		if got := d.LocaleDateOrders[locale]; got != want {
			t.Errorf("LocaleDateOrders[%q] = %q; want %q", locale, got, want)
		}
	}
}

func TestGetDateTimeData_LocaleDateSeparators(t *testing.T) {
	d, err := GetDateTimeData()
	if err != nil {
		t.Fatalf("GetDateTimeData() error = %v", err)
	}
	for _, lang := range []string{"de", "ru", "pl", "fi"} {
		if sep := d.LocaleDateSeparators[lang]; sep != "." {
			t.Errorf("LocaleDateSeparators[%q] = %q; want \".\"", lang, sep)
		}
	}
}

func TestGetDateTimeData_SupportedDateFormats(t *testing.T) {
	d, err := GetDateTimeData()
	if err != nil {
		t.Fatalf("GetDateTimeData() error = %v", err)
	}
	if len(d.SupportedDateFormats) != 16 {
		t.Errorf("SupportedDateFormats length = %d; want 16", len(d.SupportedDateFormats))
	}
	// Spot-check first entry.
	first := d.SupportedDateFormats[0]
	if first.Format != "YYYY/MM/DD" {
		t.Errorf("first format = %q; want \"YYYY/MM/DD\"", first.Format)
	}
	if first.YearIndex != 1 || first.MonthIndex != 2 || first.DayIndex != 3 {
		t.Errorf("first format indices = (%d,%d,%d); want (1,2,3)",
			first.YearIndex, first.MonthIndex, first.DayIndex)
	}
	// Last entry should be the ISO 8601 timestamp.
	last := d.SupportedDateFormats[15]
	if last.Format != "YYYY-MM-DDTHH:MM:SS" {
		t.Errorf("last format = %q; want \"YYYY-MM-DDTHH:MM:SS\"", last.Format)
	}
	if last.HourIndex != 4 {
		t.Errorf("ISO format HourIndex = %d; want 4", last.HourIndex)
	}
}
