// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: datetime.proto

package datetime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DateTimeData holds locale-specific datetime configuration.
// Data file: data/data.json
type DateTimeData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// locale_date_orders maps a locale code (e.g. "en-US", "de") to its
	// conventional date field ordering: "MDY", "DMY", or "YMD".
	LocaleDateOrders map[string]string `protobuf:"bytes,1,rep,name=locale_date_orders,proto3" json:"locale_date_orders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// locale_date_separators maps a locale code to its conventional date
	// separator character (e.g. "/", ".", "-").
	LocaleDateSeparators map[string]string `protobuf:"bytes,2,rep,name=locale_date_separators,proto3" json:"locale_date_separators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// supported_date_formats lists recognised date/datetime format patterns.
	SupportedDateFormats []*SupportedDateFormat `protobuf:"bytes,3,rep,name=supported_date_formats,proto3" json:"supported_date_formats,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DateTimeData) Reset() {
	*x = DateTimeData{}
	mi := &file_datetime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTimeData) ProtoMessage() {}

func (x *DateTimeData) ProtoReflect() protoreflect.Message {
	mi := &file_datetime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTimeData.ProtoReflect.Descriptor instead.
func (*DateTimeData) Descriptor() ([]byte, []int) {
	return file_datetime_proto_rawDescGZIP(), []int{0}
}

func (x *DateTimeData) GetLocaleDateOrders() map[string]string {
	if x != nil {
		return x.LocaleDateOrders
	}
	return nil
}

func (x *DateTimeData) GetLocaleDateSeparators() map[string]string {
	if x != nil {
		return x.LocaleDateSeparators
	}
	return nil
}

func (x *DateTimeData) GetSupportedDateFormats() []*SupportedDateFormat {
	if x != nil {
		return x.SupportedDateFormats
	}
	return nil
}

// SupportedDateFormat describes a regex pattern and its component capture-group indices.
type SupportedDateFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regex         string                 `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	YearIndex     int32                  `protobuf:"varint,2,opt,name=year_index,proto3" json:"year_index,omitempty"`
	MonthIndex    int32                  `protobuf:"varint,3,opt,name=month_index,proto3" json:"month_index,omitempty"`
	DayIndex      int32                  `protobuf:"varint,4,opt,name=day_index,proto3" json:"day_index,omitempty"`
	HourIndex     int32                  `protobuf:"varint,5,opt,name=hour_index,proto3" json:"hour_index,omitempty"`
	MinuteIndex   int32                  `protobuf:"varint,6,opt,name=minute_index,proto3" json:"minute_index,omitempty"`
	SecondIndex   int32                  `protobuf:"varint,7,opt,name=second_index,proto3" json:"second_index,omitempty"`
	Format        string                 `protobuf:"bytes,8,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedDateFormat) Reset() {
	*x = SupportedDateFormat{}
	mi := &file_datetime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedDateFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedDateFormat) ProtoMessage() {}

func (x *SupportedDateFormat) ProtoReflect() protoreflect.Message {
	mi := &file_datetime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedDateFormat.ProtoReflect.Descriptor instead.
func (*SupportedDateFormat) Descriptor() ([]byte, []int) {
	return file_datetime_proto_rawDescGZIP(), []int{1}
}

func (x *SupportedDateFormat) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

func (x *SupportedDateFormat) GetYearIndex() int32 {
	if x != nil {
		return x.YearIndex
	}
	return 0
}

func (x *SupportedDateFormat) GetMonthIndex() int32 {
	if x != nil {
		return x.MonthIndex
	}
	return 0
}

func (x *SupportedDateFormat) GetDayIndex() int32 {
	if x != nil {
		return x.DayIndex
	}
	return 0
}

func (x *SupportedDateFormat) GetHourIndex() int32 {
	if x != nil {
		return x.HourIndex
	}
	return 0
}

func (x *SupportedDateFormat) GetMinuteIndex() int32 {
	if x != nil {
		return x.MinuteIndex
	}
	return 0
}

func (x *SupportedDateFormat) GetSecondIndex() int32 {
	if x != nil {
		return x.SecondIndex
	}
	return 0
}

func (x *SupportedDateFormat) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_datetime_proto protoreflect.FileDescriptor

const file_datetime_proto_rawDesc = "" +
	"\n" +
	"\x0edatetime.proto\x12\bdatetime\"\xbb\x03\n" +
	"\fDateTimeData\x12\\\n" +
	"\x12locale_date_orders\x18\x01 \x03(\v2,.datetime.DateTimeData.LocaleDateOrdersEntryR\x12locale_date_orders\x12h\n" +
	"\x16locale_date_separators\x18\x02 \x03(\v20.datetime.DateTimeData.LocaleDateSeparatorsEntryR\x16locale_date_separators\x12U\n" +
	"\x16supported_date_formats\x18\x03 \x03(\v2\x1d.datetime.SupportedDateFormatR\x16supported_date_formats\x1aC\n" +
	"\x15LocaleDateOrdersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19LocaleDateSeparatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x13SupportedDateFormat\x12\x14\n" +
	"\x05regex\x18\x01 \x01(\tR\x05regex\x12\x1e\n" +
	"\n" +
	"year_index\x18\x02 \x01(\x05R\n" +
	"year_index\x12 \n" +
	"\vmonth_index\x18\x03 \x01(\x05R\vmonth_index\x12\x1c\n" +
	"\tday_index\x18\x04 \x01(\x05R\tday_index\x12\x1e\n" +
	"\n" +
	"hour_index\x18\x05 \x01(\x05R\n" +
	"hour_index\x12\"\n" +
	"\fminute_index\x18\x06 \x01(\x05R\fminute_index\x12\"\n" +
	"\fsecond_index\x18\a \x01(\x05R\fsecond_index\x12\x16\n" +
	"\x06format\x18\b \x01(\tR\x06formatB?Z=github.com/razorpay/i18nify/i18nify-data/go/datetime;datetimeb\x06proto3"

var (
	file_datetime_proto_rawDescOnce sync.Once
	file_datetime_proto_rawDescData []byte
)

func file_datetime_proto_rawDescGZIP() []byte {
	file_datetime_proto_rawDescOnce.Do(func() {
		file_datetime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datetime_proto_rawDesc), len(file_datetime_proto_rawDesc)))
	})
	return file_datetime_proto_rawDescData
}

var file_datetime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_datetime_proto_goTypes = []any{
	(*DateTimeData)(nil),        // 0: datetime.DateTimeData
	(*SupportedDateFormat)(nil), // 1: datetime.SupportedDateFormat
	nil,                         // 2: datetime.DateTimeData.LocaleDateOrdersEntry
	nil,                         // 3: datetime.DateTimeData.LocaleDateSeparatorsEntry
}
var file_datetime_proto_depIdxs = []int32{
	2, // 0: datetime.DateTimeData.locale_date_orders:type_name -> datetime.DateTimeData.LocaleDateOrdersEntry
	3, // 1: datetime.DateTimeData.locale_date_separators:type_name -> datetime.DateTimeData.LocaleDateSeparatorsEntry
	1, // 2: datetime.DateTimeData.supported_date_formats:type_name -> datetime.SupportedDateFormat
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datetime_proto_init() }
func file_datetime_proto_init() {
	if File_datetime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datetime_proto_rawDesc), len(file_datetime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datetime_proto_goTypes,
		DependencyIndexes: file_datetime_proto_depIdxs,
		MessageInfos:      file_datetime_proto_msgTypes,
	}.Build()
	File_datetime_proto = out.File
	file_datetime_proto_goTypes = nil
	file_datetime_proto_depIdxs = nil
}
