export const ALLOWED_FORMAT_PARTS_KEYS = [
  'nan',
  'infinity',
  'percent',
  'integer',
  'group',
  'decimal',
  'fraction',
  'plusSign',
  'minusSign',
  'percentSign',
  'currency',
  'code',
  'symbol',
  'name',
  'compact',
  'exponentInteger',
  'exponentMinusSign',
  'exponentSeparator',
  'unit',
] as const;
