// Code generated by i18nify go generator. DO NOT EDIT.

package bankcodes

import (
	"testing"
)

// TestGetBankCodes_AllCountryCodes tests that all available country codes
// can be loaded successfully. This ensures the JSON data is valid and matches
// the proto schema.
func TestGetBankCodes_AllCountryCodes(t *testing.T) {
	// Get all available country codes
	codes, err := GetAvailableCountryCodes()
	if err != nil {
		t.Fatalf("GetAvailableCountryCodes() error = %v", err)
	}

	if len(codes) == 0 {
		t.Fatal("GetAvailableCountryCodes() returned empty list")
	}

	t.Logf("Found %d country codes: %v", len(codes), codes)

	// Test loading data for each country code
	for _, code := range codes {
		t.Run(code, func(t *testing.T) {
			data, err := GetBankCodes(code)
			if err != nil {
				t.Errorf("GetBankCodes(%q) error = %v", code, err)
				return
			}
			if data == nil {
				t.Errorf("GetBankCodes(%q) returned nil data", code)
			}
		})
	}
}

// TestGetBankCodes_InvalidCode tests that an invalid country code
// returns an appropriate error.
func TestGetBankCodes_InvalidCode(t *testing.T) {
	_, err := GetBankCodes("INVALID_CODE_XYZ_123")
	if err == nil {
		t.Error("GetBankCodes(\"INVALID_CODE_XYZ_123\") expected error, got nil")
	}
}

// TestGetBankCodes_CaseInsensitive tests that country codes are
// handled case-insensitively.
func TestGetBankCodes_CaseInsensitive(t *testing.T) {
	codes, err := GetAvailableCountryCodes()
	if err != nil || len(codes) == 0 {
		t.Skip("No country codes available")
	}

	code := codes[0]
	
	// Test uppercase
	data1, err1 := GetBankCodes(code)
	if err1 != nil {
		t.Fatalf("GetBankCodes(%q) error = %v", code, err1)
	}

	// Test lowercase (should return same data from cache)
	lowerCode := code // codes are already uppercase
	data2, err2 := GetBankCodes(lowerCode)
	if err2 != nil {
		t.Fatalf("GetBankCodes(%q) error = %v", lowerCode, err2)
	}

	// Both should return valid data
	if data1 == nil || data2 == nil {
		t.Error("Expected non-nil data for both cases")
	}
}
