// Code generated by i18nify go generator. DO NOT EDIT.

package names

import (
	"testing"
)

// TestGetNamesData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetNamesData(t *testing.T) {
	data, err := GetNamesData()
	if err != nil {
		t.Fatalf("GetNamesData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetNamesData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetNamesData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetNamesData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetNamesData()
	if err1 != nil {
		t.Fatalf("First GetNamesData() error = %v", err1)
	}

	data2, err2 := GetNamesData()
	if err2 != nil {
		t.Fatalf("Second GetNamesData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetNamesData() should return cached data on subsequent calls")
	}
}

// TestGetNamesData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetNamesData_NotEmpty(t *testing.T) {
	data, err := GetNamesData()
	if err != nil {
		t.Fatalf("GetNamesData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
