// Code generated by i18nify go generator. DO NOT EDIT.

package names

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *NamesData
	dataOnce sync.Once
	dataErr  error
)

// GetNamesData retrieves the data.
func GetNamesData() (*NamesData, error) {
	dataOnce.Do(func() {
		data = &NamesData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
