// Code generated by i18nify go generator. DO NOT EDIT.

package names

import (
	"testing"
)

func TestGetNamesData(t *testing.T) {
	d, err := GetNamesData()
	if err != nil {
		t.Fatalf("GetNamesData() error = %v", err)
	}
	if d == nil {
		t.Fatal("GetNamesData() returned nil")
	}
}

func TestGetNamesData_Idempotent(t *testing.T) {
	d1, err1 := GetNamesData()
	if err1 != nil {
		t.Fatalf("first call error: %v", err1)
	}
	d2, err2 := GetNamesData()
	if err2 != nil {
		t.Fatalf("second call error: %v", err2)
	}
	if d1 != d2 {
		t.Error("GetNamesData() must return the same cached pointer on repeated calls")
	}
}

func TestGetNamesData_HonorificTitles(t *testing.T) {
	d, err := GetNamesData()
	if err != nil {
		t.Fatalf("GetNamesData() error = %v", err)
	}
	for _, locale := range []string{"english", "hindi", "french", "german", "spanish", "arabic", "japanese", "chinese"} {
		titles, ok := d.NamesInformation.HonorificTitles[locale]
		if !ok {
			t.Errorf("HonorificTitles must contain locale %q", locale)
			continue
		}
		if len(titles) == 0 {
			t.Errorf("HonorificTitles[%q] must not be empty", locale)
		}
		for _, tt := range titles {
			if tt.Code == "" {
				t.Errorf("HonorificTitles[%q]: entry has empty Code", locale)
			}
			if tt.Title == "" {
				t.Errorf("HonorificTitles[%q]: entry %q has empty Title", locale, tt.Code)
			}
		}
	}
}

func TestGetNamesData_ValidationRules(t *testing.T) {
	d, err := GetNamesData()
	if err != nil {
		t.Fatalf("GetNamesData() error = %v", err)
	}
	rules := d.NamesInformation.ValidationRules
	if rules.MinLength <= 0 {
		t.Errorf("ValidationRules.MinLength = %d; want > 0", rules.MinLength)
	}
	if rules.MaxLength <= 0 {
		t.Errorf("ValidationRules.MaxLength = %d; want > 0", rules.MaxLength)
	}
	if rules.MinLength >= rules.MaxLength {
		t.Errorf("MinLength (%d) must be less than MaxLength (%d)", rules.MinLength, rules.MaxLength)
	}
}
