// Code generated by i18nify go generator. DO NOT EDIT.

package names

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *NamesData
	dataOnce sync.Once
	dataErr  error
)

// GetNamesData retrieves the names configuration data.
// The JSON is parsed exactly once; subsequent calls return the cached result.
func GetNamesData() (*NamesData, error) {
	dataOnce.Do(func() {
		data = &NamesData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
