// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: names.proto

package names

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NamesData is the top-level container for all names-related reference data.
// Data files: data.json
type NamesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamesInformation *NamesInformation `protobuf:"bytes,1,opt,name=names_information,json=namesInformation,proto3" json:"names_information,omitempty"`
}

func (x *NamesData) Reset() {
	*x = NamesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_names_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamesData) ProtoMessage() {}

func (x *NamesData) ProtoReflect() protoreflect.Message {
	mi := &file_names_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamesData.ProtoReflect.Descriptor instead.
func (*NamesData) Descriptor() ([]byte, []int) {
	return file_names_proto_rawDescGZIP(), []int{0}
}

func (x *NamesData) GetNamesInformation() *NamesInformation {
	if x != nil {
		return x.NamesInformation
	}
	return nil
}

// NamesInformation holds name validation rules.
type NamesInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// validation_rules defines length constraints applied to name fields.
	ValidationRules *ValidationRules `protobuf:"bytes,1,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
}

func (x *NamesInformation) Reset() {
	*x = NamesInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_names_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamesInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamesInformation) ProtoMessage() {}

func (x *NamesInformation) ProtoReflect() protoreflect.Message {
	mi := &file_names_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamesInformation.ProtoReflect.Descriptor instead.
func (*NamesInformation) Descriptor() ([]byte, []int) {
	return file_names_proto_rawDescGZIP(), []int{1}
}

func (x *NamesInformation) GetValidationRules() *ValidationRules {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

// ValidationRules defines the character-length bounds for a person's name.
type ValidationRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinLength int32 `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength int32 `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
}

func (x *ValidationRules) Reset() {
	*x = ValidationRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_names_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRules) ProtoMessage() {}

func (x *ValidationRules) ProtoReflect() protoreflect.Message {
	mi := &file_names_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRules.ProtoReflect.Descriptor instead.
func (*ValidationRules) Descriptor() ([]byte, []int) {
	return file_names_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationRules) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *ValidationRules) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

var File_names_proto protoreflect.FileDescriptor

var file_names_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x44, 0x0a, 0x11, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x10, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x0f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x4f,
	0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61,
	0x7a, 0x6f, 0x72, 0x70, 0x61, 0x79, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x69, 0x66, 0x79, 0x2f, 0x69,
	0x31, 0x38, 0x6e, 0x69, 0x66, 0x79, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x2f, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x3b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_names_proto_rawDescOnce sync.Once
	file_names_proto_rawDescData = file_names_proto_rawDesc
)

func file_names_proto_rawDescGZIP() []byte {
	file_names_proto_rawDescOnce.Do(func() {
		file_names_proto_rawDescData = protoimpl.X.CompressGZIP(file_names_proto_rawDescData)
	})
	return file_names_proto_rawDescData
}

var file_names_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_names_proto_goTypes = []interface{}{
	(*NamesData)(nil),        // 0: names.NamesData
	(*NamesInformation)(nil), // 1: names.NamesInformation
	(*ValidationRules)(nil),  // 2: names.ValidationRules
}
var file_names_proto_depIdxs = []int32{
	1, // 0: names.NamesData.names_information:type_name -> names.NamesInformation
	2, // 1: names.NamesInformation.validation_rules:type_name -> names.ValidationRules
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_names_proto_init() }
func file_names_proto_init() {
	if File_names_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_names_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_names_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamesInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_names_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_names_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_names_proto_goTypes,
		DependencyIndexes: file_names_proto_depIdxs,
		MessageInfos:      file_names_proto_msgTypes,
	}.Build()
	File_names_proto = out.File
	file_names_proto_rawDesc = nil
	file_names_proto_goTypes = nil
	file_names_proto_depIdxs = nil
}
