// Code generated by i18nify go generator. DO NOT EDIT.

package paymenttranslations

import (
	"testing"
)

func TestGetPaymentTranslationsData(t *testing.T) {
	data, err := GetPaymentTranslationsData()
	if err != nil {
		t.Fatalf("GetPaymentTranslationsData() error = %v", err)
	}
	if data == nil {
		t.Fatal("GetPaymentTranslationsData() returned nil data")
	}
	t.Log("Data loaded successfully")
}

func TestGetPaymentTranslationsData_Idempotent(t *testing.T) {
	data1, err1 := GetPaymentTranslationsData()
	if err1 != nil {
		t.Fatalf("First GetPaymentTranslationsData() error = %v", err1)
	}
	data2, err2 := GetPaymentTranslationsData()
	if err2 != nil {
		t.Fatalf("Second GetPaymentTranslationsData() error = %v", err2)
	}
	if data1 != data2 {
		t.Error("GetPaymentTranslationsData() should return cached data on subsequent calls")
	}
}

func TestGetPaymentTranslationsData_NotEmpty(t *testing.T) {
	data, err := GetPaymentTranslationsData()
	if err != nil {
		t.Fatalf("GetPaymentTranslationsData() error = %v", err)
	}
	if data == nil {
		t.Error("Data should not be nil")
	}
	if len(data.GetPaymentTranslationInformation()) == 0 {
		t.Error("PaymentTranslationInformation should not be empty")
	}
}
