// Code generated by i18nify go generator. DO NOT EDIT.

package paymenttranslations

import (
	"testing"
)

func TestGetPaymentTranslationsData(t *testing.T) {
	data, err := GetPaymentTranslationsData()
	if err != nil {
		t.Fatalf("GetPaymentTranslationsData() error = %v", err)
	}
	if data == nil {
		t.Fatal("GetPaymentTranslationsData() returned nil data")
	}
	t.Log("Data loaded successfully")
}

func TestGetPaymentTranslationsData_Idempotent(t *testing.T) {
	data1, _ := GetPaymentTranslationsData()
	data2, _ := GetPaymentTranslationsData()
	if data1 != data2 {
		t.Error("GetPaymentTranslationsData() should return cached data on subsequent calls")
	}
}

func TestGetPaymentTranslationsData_NotEmpty(t *testing.T) {
	data, err := GetPaymentTranslationsData()
	if err != nil {
		t.Fatalf("GetPaymentTranslationsData() error = %v", err)
	}
	if len(data.GetPaymentTranslationsInformation()) == 0 {
		t.Error("PaymentTranslationsInformation should not be empty")
	}
}
