// Code generated by i18nify go generator. DO NOT EDIT.

package paymenttranslations

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *PaymentTranslationsData
	dataOnce sync.Once
	dataErr  error
)

// GetPaymentTranslationsData retrieves the paymenttranslations data.
func GetPaymentTranslationsData() (*PaymentTranslationsData, error) {
	dataOnce.Do(func() {
		data = &PaymentTranslationsData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
