// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: phone-number.proto

package phonenumber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CountryTeleInformation contains dial code, format, and regex for telephone numbers of a specific country.
type CountryTeleInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialCode string `protobuf:"bytes,1,opt,name=dial_code,json=dialCode,proto3" json:"dial_code,omitempty"` // DialCode represents the international dialing code for the country.
	Format   string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                     // Format represents the format of telephone numbers in the country.
	Regex    string `protobuf:"bytes,3,opt,name=regex,proto3" json:"regex,omitempty"`                       // Regex represents the regular expression pattern for validating telephone numbers in the country.
}

func (x *CountryTeleInformation) Reset() {
	*x = CountryTeleInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountryTeleInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryTeleInformation) ProtoMessage() {}

func (x *CountryTeleInformation) ProtoReflect() protoreflect.Message {
	mi := &file_phone_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryTeleInformation.ProtoReflect.Descriptor instead.
func (*CountryTeleInformation) Descriptor() ([]byte, []int) {
	return file_phone_number_proto_rawDescGZIP(), []int{0}
}

func (x *CountryTeleInformation) GetDialCode() string {
	if x != nil {
		return x.DialCode
	}
	return ""
}

func (x *CountryTeleInformation) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CountryTeleInformation) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

var File_phone_number_proto protoreflect.FileDescriptor

var file_phone_number_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x63, 0x0a, 0x16, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x65, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x69, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phone_number_proto_rawDescOnce sync.Once
	file_phone_number_proto_rawDescData = file_phone_number_proto_rawDesc
)

func file_phone_number_proto_rawDescGZIP() []byte {
	file_phone_number_proto_rawDescOnce.Do(func() {
		file_phone_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_phone_number_proto_rawDescData)
	})
	return file_phone_number_proto_rawDescData
}

var file_phone_number_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_phone_number_proto_goTypes = []interface{}{
	(*CountryTeleInformation)(nil), // 0: phonenumber.CountryTeleInformation
}
var file_phone_number_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phone_number_proto_init() }
func file_phone_number_proto_init() {
	if File_phone_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phone_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountryTeleInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phone_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_phone_number_proto_goTypes,
		DependencyIndexes: file_phone_number_proto_depIdxs,
		MessageInfos:      file_phone_number_proto_msgTypes,
	}.Build()
	File_phone_number_proto = out.File
	file_phone_number_proto_rawDesc = nil
	file_phone_number_proto_goTypes = nil
	file_phone_number_proto_depIdxs = nil
}
