name: Execute steps if 'packages/i18nify-js' folder was changed
on:
  pull_request:

jobs:
  execute-if-i18nify-js:
    name: Execute Steps if 'packages/i18nify-js' Folder Changed
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'packages/i18nify-js/**'

      # Run only if some file in 'packages/i18nify-js' folder was changed
      - name: Execute if 'packages/i18nify-js' folder was changed
        if: steps.changes.outputs.src == 'true'
        run: |
          ${{ steps.executeSteps }}

      # If 'src' folder wasn't changed, pass the action
      - name: Skip if 'src' folder was not changed
        if: steps.changes.outputs.src == 'false'
        run: echo "No changes in 'packages/i18nify-js' folder, skipping execution"
