// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CurrencyInfo mirrors the structure inside currency_information map.
type CurrencyInfo struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Name                          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumericCode                   string                 `protobuf:"bytes,2,opt,name=numeric_code,json=numericCode,proto3" json:"numeric_code,omitempty"` // stored as string in source JSON
	MinorUnit                     string                 `protobuf:"bytes,3,opt,name=minor_unit,json=minorUnit,proto3" json:"minor_unit,omitempty"`       // stored as string in source JSON
	Symbol                        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PhysicalCurrencyDenominations []string               `protobuf:"bytes,5,rep,name=physical_currency_denominations,json=physicalCurrencyDenominations,proto3" json:"physical_currency_denominations,omitempty"` // strings include decimals/"nan"
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CurrencyInfo) Reset() {
	*x = CurrencyInfo{}
	mi := &file_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyInfo) ProtoMessage() {}

func (x *CurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyInfo.ProtoReflect.Descriptor instead.
func (*CurrencyInfo) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

func (x *CurrencyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrencyInfo) GetNumericCode() string {
	if x != nil {
		return x.NumericCode
	}
	return ""
}

func (x *CurrencyInfo) GetMinorUnit() string {
	if x != nil {
		return x.MinorUnit
	}
	return ""
}

func (x *CurrencyInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CurrencyInfo) GetPhysicalCurrencyDenominations() []string {
	if x != nil {
		return x.PhysicalCurrencyDenominations
	}
	return nil
}

var File_currency_proto protoreflect.FileDescriptor

const file_currency_proto_rawDesc = "" +
	"\n" +
	"\x0ecurrency.proto\x12\bcurrency\"\xc4\x01\n" +
	"\fCurrencyInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fnumeric_code\x18\x02 \x01(\tR\vnumericCode\x12\x1d\n" +
	"\n" +
	"minor_unit\x18\x03 \x01(\tR\tminorUnit\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12F\n" +
	"\x1fphysical_currency_denominations\x18\x05 \x03(\tR\x1dphysicalCurrencyDenominationsB\fZ\n" +
	"./currencyb\x06proto3"

var (
	file_currency_proto_rawDescOnce sync.Once
	file_currency_proto_rawDescData []byte
)

func file_currency_proto_rawDescGZIP() []byte {
	file_currency_proto_rawDescOnce.Do(func() {
		file_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)))
	})
	return file_currency_proto_rawDescData
}

var file_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_currency_proto_goTypes = []any{
	(*CurrencyInfo)(nil), // 0: currency.CurrencyInfo
}
var file_currency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_currency_proto_init() }
func file_currency_proto_init() {
	if File_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_currency_proto_goTypes,
		DependencyIndexes: file_currency_proto_depIdxs,
		MessageInfos:      file_currency_proto_msgTypes,
	}.Build()
	File_currency_proto = out.File
	file_currency_proto_goTypes = nil
	file_currency_proto_depIdxs = nil
}
