// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: currency.proto.tmp

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CurrencyInfo mirrors the structure inside currency_information map.
type CurrencyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                          string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumericCode                   string   `protobuf:"bytes,2,opt,name=numeric_code,json=numericCode,proto3" json:"numeric_code,omitempty"` // stored as string in source JSON
	MinorUnit                     string   `protobuf:"bytes,3,opt,name=minor_unit,json=minorUnit,proto3" json:"minor_unit,omitempty"`       // stored as string in source JSON
	Symbol                        string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PhysicalCurrencyDenominations []string `protobuf:"bytes,5,rep,name=physical_currency_denominations,json=physicalCurrencyDenominations,proto3" json:"physical_currency_denominations,omitempty"` // strings include decimals/"nan"
}

func (x *CurrencyInfo) Reset() {
	*x = CurrencyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currency_proto_tmp_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyInfo) ProtoMessage() {}

func (x *CurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_tmp_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyInfo.ProtoReflect.Descriptor instead.
func (*CurrencyInfo) Descriptor() ([]byte, []int) {
	return file_currency_proto_tmp_rawDescGZIP(), []int{0}
}

func (x *CurrencyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrencyInfo) GetNumericCode() string {
	if x != nil {
		return x.NumericCode
	}
	return ""
}

func (x *CurrencyInfo) GetMinorUnit() string {
	if x != nil {
		return x.MinorUnit
	}
	return ""
}

func (x *CurrencyInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CurrencyInfo) GetPhysicalCurrencyDenominations() []string {
	if x != nil {
		return x.PhysicalCurrencyDenominations
	}
	return nil
}

var File_currency_proto_tmp protoreflect.FileDescriptor

var file_currency_proto_tmp_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x74, 0x6d, 0x70, 0x12, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0xc4,
	0x01, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x65, 0x72,
	0x69, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x5f,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x6f,
	0x72, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x46, 0x0a,
	0x1f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x1d, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x7a, 0x6f, 0x72, 0x70, 0x61, 0x79, 0x2f, 0x69, 0x31, 0x38,
	0x6e, 0x69, 0x66, 0x79, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x69, 0x66, 0x79, 0x2d, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_currency_proto_tmp_rawDescOnce sync.Once
	file_currency_proto_tmp_rawDescData = file_currency_proto_tmp_rawDesc
)

func file_currency_proto_tmp_rawDescGZIP() []byte {
	file_currency_proto_tmp_rawDescOnce.Do(func() {
		file_currency_proto_tmp_rawDescData = protoimpl.X.CompressGZIP(file_currency_proto_tmp_rawDescData)
	})
	return file_currency_proto_tmp_rawDescData
}

var file_currency_proto_tmp_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_currency_proto_tmp_goTypes = []interface{}{
	(*CurrencyInfo)(nil), // 0: currency.CurrencyInfo
}
var file_currency_proto_tmp_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_currency_proto_tmp_init() }
func file_currency_proto_tmp_init() {
	if File_currency_proto_tmp != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_currency_proto_tmp_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_currency_proto_tmp_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_currency_proto_tmp_goTypes,
		DependencyIndexes: file_currency_proto_tmp_depIdxs,
		MessageInfos:      file_currency_proto_tmp_msgTypes,
	}.Build()
	File_currency_proto_tmp = out.File
	file_currency_proto_tmp_rawDesc = nil
	file_currency_proto_tmp_goTypes = nil
	file_currency_proto_tmp_depIdxs = nil
}
