// Code generated by i18nify go generator. DO NOT EDIT.

package currency

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *CurrencyData
	dataOnce sync.Once
	dataErr  error
)

// GetCurrencyData retrieves the data.
func GetCurrencyData() (*CurrencyData, error) {
	dataOnce.Do(func() {
		data = &CurrencyData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
