// Code generated by i18nify go generator. DO NOT EDIT.

package currency

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *CurrencyData
	dataOnce sync.Once
	dataErr  error
)

// GetCurrencyData retrieves the data.
func GetCurrencyData() (*CurrencyData, error) {
	dataOnce.Do(func() {
		data = &CurrencyData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
