// Code generated by i18nify go generator. DO NOT EDIT.

package currency

import (
	"testing"
)

// TestGetCurrencyData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetCurrencyData(t *testing.T) {
	data, err := GetCurrencyData()
	if err != nil {
		t.Fatalf("GetCurrencyData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetCurrencyData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetCurrencyData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetCurrencyData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetCurrencyData()
	if err1 != nil {
		t.Fatalf("First GetCurrencyData() error = %v", err1)
	}

	data2, err2 := GetCurrencyData()
	if err2 != nil {
		t.Fatalf("Second GetCurrencyData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetCurrencyData() should return cached data on subsequent calls")
	}
}

// TestGetCurrencyData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetCurrencyData_NotEmpty(t *testing.T) {
	data, err := GetCurrencyData()
	if err != nil {
		t.Fatalf("GetCurrencyData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
