// Code generated by generateGoFromSchema.js. DO NOT EDIT.

package metadata

import (
    "embed"
    "encoding/json"
)

// MetadataData represents root structure
type MetadataData struct {
    MetadataInformation interface{} `json:"metadata_information"`
}

// GetMetadataInformation returns the metadata_information
func (d *MetadataData) GetMetadataInformation() interface{} {
    return d.MetadataInformation
}


//go:embed "data/*.json"
var metadataFS embed.FS

// MetadataDataInstance contains the generated data
var MetadataDataInstance MetadataData

func init() {
    data, err := metadataFS.ReadFile("data/data.json")
    if err != nil {
        panic(err)
    }

    if err := json.Unmarshal(data, &MetadataDataInstance); err != nil {
        panic(err)
    }
}

// GetMetadataData returns the instance of MetadataData
func GetMetadataData() *MetadataData {
    return &MetadataDataInstance
}