// Code generated by i18nify go generator. DO NOT EDIT.

package phone_number_country_code_to_phone_number

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *CountryPhoneData
	dataOnce sync.Once
	dataErr  error
)

// GetCountryPhoneData retrieves the data.
func GetCountryPhoneData() (*CountryPhoneData, error) {
	dataOnce.Do(func() {
		data = &CountryPhoneData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
