// Code generated by i18nify go generator. DO NOT EDIT.

package phone_number_country_code_to_phone_number

import (
	"testing"
)

func TestGetCountryPhoneData(t *testing.T) {
	data, err := GetCountryPhoneData()
	if err != nil {
		t.Fatalf("GetCountryPhoneData() error = %v", err)
	}
	if data == nil {
		t.Fatal("GetCountryPhoneData() returned nil data")
	}
	t.Log("Data loaded successfully")
}

func TestGetCountryPhoneData_Idempotent(t *testing.T) {
	data1, err1 := GetCountryPhoneData()
	if err1 != nil {
		t.Fatalf("First GetCountryPhoneData() error = %v", err1)
	}
	data2, err2 := GetCountryPhoneData()
	if err2 != nil {
		t.Fatalf("Second GetCountryPhoneData() error = %v", err2)
	}
	if data1 != data2 {
		t.Error("GetCountryPhoneData() should return cached data on subsequent calls")
	}
}

func TestGetCountryPhoneData_NotEmpty(t *testing.T) {
	data, err := GetCountryPhoneData()
	if err != nil {
		t.Fatalf("GetCountryPhoneData() error = %v", err)
	}
	if data == nil {
		t.Error("Data should not be nil")
	}
}
