// Code generated by i18nify go generator. DO NOT EDIT.

package address

import (
	"testing"
)

func TestGetAddressData(t *testing.T) {
	data, err := GetAddressData()
	if err != nil {
		t.Fatalf("GetAddressData() error = %v", err)
	}
	if data == nil {
		t.Fatal("GetAddressData() returned nil data")
	}
	t.Log("Data loaded successfully")
}

func TestGetAddressData_Idempotent(t *testing.T) {
	data1, err1 := GetAddressData()
	if err1 != nil {
		t.Fatalf("First GetAddressData() error = %v", err1)
	}
	data2, err2 := GetAddressData()
	if err2 != nil {
		t.Fatalf("Second GetAddressData() error = %v", err2)
	}
	if data1 != data2 {
		t.Error("GetAddressData() should return cached data on subsequent calls")
	}
}

func TestGetAddressData_NotEmpty(t *testing.T) {
	data, err := GetAddressData()
	if err != nil {
		t.Fatalf("GetAddressData() error = %v", err)
	}
	if data == nil {
		t.Error("Data should not be nil")
	}
	if len(data.GetAddressFormatInformation()) == 0 {
		t.Error("AddressFormatInformation should not be empty")
	}
}
