// Code generated by i18nify utility-creator. DO NOT EDIT.

package address

import (
	"testing"
)

func TestGetAddressData(t *testing.T) {
	data, err := GetAddressData()
	if err != nil {
		t.Fatalf("GetAddressData() error = %v", err)
	}
	if data == nil {
		t.Fatal("GetAddressData() returned nil")
	}
}

func TestGetAddressData_Idempotent(t *testing.T) {
	d1, err1 := GetAddressData()
	if err1 != nil {
		t.Fatalf("first call error: %v", err1)
	}
	d2, err2 := GetAddressData()
	if err2 != nil {
		t.Fatalf("second call error: %v", err2)
	}
	if d1 != d2 {
		t.Error("GetAddressData() must return the same cached pointer")
	}
}

func TestGetAddressData_NotEmpty(t *testing.T) {
	data, err := GetAddressData()
	if err != nil {
		t.Fatalf("GetAddressData() error = %v", err)
	}
	if data == nil {
		t.Error("Data should not be nil")
	}
	if len(data.GetAddressFormatInformation()) == 0 {
		t.Error("AddressFormatInformation should not be empty")
	}
}
