// Code generated by i18nify go generator. DO NOT EDIT.

package address

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *AddressData
	dataOnce sync.Once
	dataErr  error
)

// GetAddressData retrieves the address format data.
func GetAddressData() (*AddressData, error) {
	dataOnce.Do(func() {
		data = &AddressData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
