// Code generated by i18nify utility-creator. DO NOT EDIT.

package address

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *AddressData
	dataOnce sync.Once
	dataErr  error
)

// GetAddressData retrieves the address data (singleton, thread-safe).
func GetAddressData() (*AddressData, error) {
	dataOnce.Do(func() {
		data = &AddressData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
