// Code generated by i18nify go generator. DO NOT EDIT.

package payment_translations

import (
	"testing"
)

// TestGetPaymentTranslationsConfig tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetPaymentTranslationsConfig(t *testing.T) {
	data, err := GetPaymentTranslationsConfig()
	if err != nil {
		t.Fatalf("GetPaymentTranslationsConfig() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetPaymentTranslationsConfig() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetPaymentTranslationsConfig_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetPaymentTranslationsConfig_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetPaymentTranslationsConfig()
	if err1 != nil {
		t.Fatalf("First GetPaymentTranslationsConfig() error = %v", err1)
	}

	data2, err2 := GetPaymentTranslationsConfig()
	if err2 != nil {
		t.Fatalf("Second GetPaymentTranslationsConfig() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetPaymentTranslationsConfig() should return cached data on subsequent calls")
	}
}

// TestGetPaymentTranslationsConfig_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetPaymentTranslationsConfig_NotEmpty(t *testing.T) {
	data, err := GetPaymentTranslationsConfig()
	if err != nil {
		t.Fatalf("GetPaymentTranslationsConfig() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
