// Code generated by i18nify go generator. DO NOT EDIT.

package payment_translations

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *PaymentTranslationsConfig
	dataOnce sync.Once
	dataErr  error
)

// GetPaymentTranslationsConfig retrieves the data.
func GetPaymentTranslationsConfig() (*PaymentTranslationsConfig, error) {
	dataOnce.Do(func() {
		data = &PaymentTranslationsConfig{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
