// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity

import (
	"testing"
)

func TestGetBusinessEntityData(t *testing.T) {
	d, err := GetBusinessEntityData()
	if err != nil {
		t.Fatalf("GetBusinessEntityData() error = %v", err)
	}
	if d == nil {
		t.Fatal("GetBusinessEntityData() returned nil")
	}
}

func TestGetBusinessEntityData_Idempotent(t *testing.T) {
	d1, err1 := GetBusinessEntityData()
	if err1 != nil {
		t.Fatalf("first call error: %v", err1)
	}
	d2, err2 := GetBusinessEntityData()
	if err2 != nil {
		t.Fatalf("second call error: %v", err2)
	}
	if d1 != d2 {
		t.Error("GetBusinessEntityData() must return the same cached pointer on repeated calls")
	}
}

func TestGetBusinessEntityData_Categories(t *testing.T) {
	d, err := GetBusinessEntityData()
	if err != nil {
		t.Fatalf("GetBusinessEntityData() error = %v", err)
	}
	if len(d.BusinessEntityInformation.Categories) == 0 {
		t.Fatal("Categories must not be empty")
	}
	first := d.BusinessEntityInformation.Categories[0]
	if first.Code == "" {
		t.Error("first category Code must not be empty")
	}
	if first.Name == "" {
		t.Error("first category Name must not be empty")
	}
}

func TestGetBusinessEntityData_SubCategories(t *testing.T) {
	d, err := GetBusinessEntityData()
	if err != nil {
		t.Fatalf("GetBusinessEntityData() error = %v", err)
	}
	subs, ok := d.BusinessEntityInformation.SubCategories["CORPORATION"]
	if !ok {
		t.Fatal("SubCategories must contain key CORPORATION")
	}
	if len(subs) == 0 {
		t.Error("SubCategories[CORPORATION] must not be empty")
	}
}

func TestGetBusinessEntityData_EntityTypes(t *testing.T) {
	d, err := GetBusinessEntityData()
	if err != nil {
		t.Fatalf("GetBusinessEntityData() error = %v", err)
	}
	for _, cc := range []string{"IN", "US", "GB", "SG", "AU", "MY"} {
		types, ok := d.BusinessEntityInformation.EntityTypes[cc]
		if !ok {
			t.Errorf("EntityTypes must contain key %s", cc)
			continue
		}
		if len(types) == 0 {
			t.Errorf("EntityTypes[%s] must not be empty", cc)
		}
	}
}
