// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/categories_data.json
var categoriesJSON []byte

//go:embed data/entity_types_data.json
var entityTypesJSON []byte

var (
	data     *BusinessEntityData
	dataOnce sync.Once
	dataErr  error
)

// GetBusinessEntityData loads and merges both data files into a single
// BusinessEntityData value. The JSON is parsed exactly once; subsequent
// calls return the cached result.
func GetBusinessEntityData() (*BusinessEntityData, error) {
	dataOnce.Do(func() {
		var cats CategoriesFileData
		if dataErr = json.Unmarshal(categoriesJSON, &cats); dataErr != nil {
			return
		}

		var ets EntityTypesFileData
		if dataErr = json.Unmarshal(entityTypesJSON, &ets); dataErr != nil {
			return
		}

		data = &BusinessEntityData{
			BusinessEntityInformation: BusinessEntityInformation{
				Categories:    cats.Categories,
				SubCategories: cats.SubCategories,
				EntityTypes:   ets.EntityTypes,
			},
		}
	})
	return data, dataErr
}
