// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *BusinessEntityData
	dataOnce sync.Once
	dataErr  error
)

// GetBusinessEntityData retrieves the data.
func GetBusinessEntityData() (*BusinessEntityData, error) {
	dataOnce.Do(func() {
		data = &BusinessEntityData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
