// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity

import (
	"testing"
)

// TestGetBusinessEntityData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetBusinessEntityData(t *testing.T) {
	data, err := GetBusinessEntityData()
	if err != nil {
		t.Fatalf("GetBusinessEntityData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetBusinessEntityData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetBusinessEntityData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetBusinessEntityData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetBusinessEntityData()
	if err1 != nil {
		t.Fatalf("First GetBusinessEntityData() error = %v", err1)
	}

	data2, err2 := GetBusinessEntityData()
	if err2 != nil {
		t.Fatalf("Second GetBusinessEntityData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetBusinessEntityData() should return cached data on subsequent calls")
	}
}

// TestGetBusinessEntityData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetBusinessEntityData_NotEmpty(t *testing.T) {
	data, err := GetBusinessEntityData()
	if err != nil {
		t.Fatalf("GetBusinessEntityData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
