// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *BusinessEntityData
	dataOnce sync.Once
	dataErr  error
)

// GetBusinessEntityData retrieves the business entity configuration data.
// The JSON is parsed exactly once; subsequent calls return the cached result.
func GetBusinessEntityData() (*BusinessEntityData, error) {
	dataOnce.Do(func() {
		data = &BusinessEntityData{}
		dataErr = json.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
