// Code generated by i18nify go generator. DO NOT EDIT.

package duitnow

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *DuitNowBanks
	dataOnce sync.Once
	dataErr  error
)

// GetDuitNowBanks retrieves the data.
func GetDuitNowBanks() (*DuitNowBanks, error) {
	dataOnce.Do(func() {
		data = &DuitNowBanks{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
