// Code generated by i18nify go generator. DO NOT EDIT.

package duitnow

import (
	"testing"
)

// TestGetDuitNowBanks tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetDuitNowBanks(t *testing.T) {
	data, err := GetDuitNowBanks()
	if err != nil {
		t.Fatalf("GetDuitNowBanks() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetDuitNowBanks() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetDuitNowBanks_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetDuitNowBanks_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetDuitNowBanks()
	if err1 != nil {
		t.Fatalf("First GetDuitNowBanks() error = %v", err1)
	}

	data2, err2 := GetDuitNowBanks()
	if err2 != nil {
		t.Fatalf("Second GetDuitNowBanks() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetDuitNowBanks() should return cached data on subsequent calls")
	}
}

// TestGetDuitNowBanks_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetDuitNowBanks_NotEmpty(t *testing.T) {
	data, err := GetDuitNowBanks()
	if err != nil {
		t.Fatalf("GetDuitNowBanks() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
