// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: duitnow.proto

package duitnow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DuitNowBanks is the bank master data for DuitNow online banking (PayNet, Malaysia).
// Data file: data.json
type DuitNowBanks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportedBanks  []*SupportedBank `protobuf:"bytes,1,rep,name=supported_banks,proto3" json:"supported_banks,omitempty"`
	Banks           []*Bank          `protobuf:"bytes,2,rep,name=banks,proto3" json:"banks,omitempty"`
	ObwEnabledCodes []string         `protobuf:"bytes,3,rep,name=obw_enabled_codes,proto3" json:"obw_enabled_codes,omitempty"`
}

func (x *DuitNowBanks) Reset() {
	*x = DuitNowBanks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duitnow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DuitNowBanks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuitNowBanks) ProtoMessage() {}

func (x *DuitNowBanks) ProtoReflect() protoreflect.Message {
	mi := &file_duitnow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuitNowBanks.ProtoReflect.Descriptor instead.
func (*DuitNowBanks) Descriptor() ([]byte, []int) {
	return file_duitnow_proto_rawDescGZIP(), []int{0}
}

func (x *DuitNowBanks) GetSupportedBanks() []*SupportedBank {
	if x != nil {
		return x.SupportedBanks
	}
	return nil
}

func (x *DuitNowBanks) GetBanks() []*Bank {
	if x != nil {
		return x.Banks
	}
	return nil
}

func (x *DuitNowBanks) GetObwEnabledCodes() []string {
	if x != nil {
		return x.ObwEnabledCodes
	}
	return nil
}

// SupportedBank is a bank code accepted for DuitNow online banking, and the
// segments it is accepted for.
type SupportedBank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Retail    bool   `protobuf:"varint,2,opt,name=retail,proto3" json:"retail,omitempty"`
	Corporate bool   `protobuf:"varint,3,opt,name=corporate,proto3" json:"corporate,omitempty"`
}

func (x *SupportedBank) Reset() {
	*x = SupportedBank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duitnow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedBank) ProtoMessage() {}

func (x *SupportedBank) ProtoReflect() protoreflect.Message {
	mi := &file_duitnow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedBank.ProtoReflect.Descriptor instead.
func (*SupportedBank) Descriptor() ([]byte, []int) {
	return file_duitnow_proto_rawDescGZIP(), []int{1}
}

func (x *SupportedBank) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SupportedBank) GetRetail() bool {
	if x != nil {
		return x.Retail
	}
	return false
}

func (x *SupportedBank) GetCorporate() bool {
	if x != nil {
		return x.Corporate
	}
	return false
}

// Bank maps a canonical bank key onto its FPX and OBW codes. A bank may support
// one rail or both; an empty code means that rail is unavailable. Order is
// significant: rows can share a code, and consumers resolve such codes by row order.
type Bank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FpxCode string `protobuf:"bytes,3,opt,name=fpx_code,proto3" json:"fpx_code,omitempty"`
	ObwCode string `protobuf:"bytes,4,opt,name=obw_code,proto3" json:"obw_code,omitempty"`
}

func (x *Bank) Reset() {
	*x = Bank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duitnow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_duitnow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_duitnow_proto_rawDescGZIP(), []int{2}
}

func (x *Bank) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetFpxCode() string {
	if x != nil {
		return x.FpxCode
	}
	return ""
}

func (x *Bank) GetObwCode() string {
	if x != nil {
		return x.ObwCode
	}
	return ""
}

var File_duitnow_proto protoreflect.FileDescriptor

var file_duitnow_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x75, 0x69, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x75, 0x69, 0x74, 0x6e, 0x6f, 0x77, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x44, 0x75, 0x69,
	0x74, 0x4e, 0x6f, 0x77, 0x42, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x75, 0x69, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x52, 0x0f, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x62,
	0x61, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x75, 0x69,
	0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x52, 0x05, 0x62, 0x61, 0x6e, 0x6b, 0x73,
	0x12, 0x2c, 0x0a, 0x11, 0x6f, 0x62, 0x77, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x6f, 0x62, 0x77,
	0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x59,
	0x0a, 0x0d, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x22, 0x64, 0x0a, 0x04, 0x42, 0x61, 0x6e,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x70, 0x78, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x70, 0x78, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x77, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x77, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61,
	0x7a, 0x6f, 0x72, 0x70, 0x61, 0x79, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x69, 0x66, 0x79, 0x2f, 0x69,
	0x31, 0x38, 0x6e, 0x69, 0x66, 0x79, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x2f, 0x64,
	0x75, 0x69, 0x74, 0x6e, 0x6f, 0x77, 0x3b, 0x64, 0x75, 0x69, 0x74, 0x6e, 0x6f, 0x77, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_duitnow_proto_rawDescOnce sync.Once
	file_duitnow_proto_rawDescData = file_duitnow_proto_rawDesc
)

func file_duitnow_proto_rawDescGZIP() []byte {
	file_duitnow_proto_rawDescOnce.Do(func() {
		file_duitnow_proto_rawDescData = protoimpl.X.CompressGZIP(file_duitnow_proto_rawDescData)
	})
	return file_duitnow_proto_rawDescData
}

var file_duitnow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_duitnow_proto_goTypes = []interface{}{
	(*DuitNowBanks)(nil),  // 0: duitnow.DuitNowBanks
	(*SupportedBank)(nil), // 1: duitnow.SupportedBank
	(*Bank)(nil),          // 2: duitnow.Bank
}
var file_duitnow_proto_depIdxs = []int32{
	1, // 0: duitnow.DuitNowBanks.supported_banks:type_name -> duitnow.SupportedBank
	2, // 1: duitnow.DuitNowBanks.banks:type_name -> duitnow.Bank
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_duitnow_proto_init() }
func file_duitnow_proto_init() {
	if File_duitnow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_duitnow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DuitNowBanks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duitnow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedBank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duitnow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_duitnow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_duitnow_proto_goTypes,
		DependencyIndexes: file_duitnow_proto_depIdxs,
		MessageInfos:      file_duitnow_proto_msgTypes,
	}.Build()
	File_duitnow_proto = out.File
	file_duitnow_proto_rawDesc = nil
	file_duitnow_proto_goTypes = nil
	file_duitnow_proto_depIdxs = nil
}
