// Code generated by i18nify go generator. DO NOT EDIT.

package phone_number_dial_code_to_country

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *DialCodeToCountryData
	dataOnce sync.Once
	dataErr  error
)

// GetDialCodeToCountryData retrieves the data.
func GetDialCodeToCountryData() (*DialCodeToCountryData, error) {
	dataOnce.Do(func() {
		data = &DialCodeToCountryData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
