// Code generated by i18nify go generator. DO NOT EDIT.

package dial_code_to_country

import (
	"testing"
)

func TestGetDialCodeToCountryData(t *testing.T) {
	data, err := GetDialCodeToCountryData()
	if err != nil {
		t.Fatalf("GetDialCodeToCountryData() error = %v", err)
	}
	if data == nil {
		t.Fatal("GetDialCodeToCountryData() returned nil data")
	}
	t.Log("Data loaded successfully")
}

func TestGetDialCodeToCountryData_Idempotent(t *testing.T) {
	data1, err1 := GetDialCodeToCountryData()
	if err1 != nil {
		t.Fatalf("First GetDialCodeToCountryData() error = %v", err1)
	}
	data2, err2 := GetDialCodeToCountryData()
	if err2 != nil {
		t.Fatalf("Second GetDialCodeToCountryData() error = %v", err2)
	}
	if data1 != data2 {
		t.Error("GetDialCodeToCountryData() should return cached data on subsequent calls")
	}
}

func TestGetDialCodeToCountryData_NotEmpty(t *testing.T) {
	data, err := GetDialCodeToCountryData()
	if err != nil {
		t.Fatalf("GetDialCodeToCountryData() error = %v", err)
	}
	if data == nil {
		t.Error("Data should not be nil")
	}
}
