// Code generated by i18nify go generator. DO NOT EDIT.

package phone_number_dial_code_to_country

import (
	"testing"
)

// TestGetDialCodeToCountryData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetDialCodeToCountryData(t *testing.T) {
	data, err := GetDialCodeToCountryData()
	if err != nil {
		t.Fatalf("GetDialCodeToCountryData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetDialCodeToCountryData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetDialCodeToCountryData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetDialCodeToCountryData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetDialCodeToCountryData()
	if err1 != nil {
		t.Fatalf("First GetDialCodeToCountryData() error = %v", err1)
	}

	data2, err2 := GetDialCodeToCountryData()
	if err2 != nil {
		t.Fatalf("Second GetDialCodeToCountryData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetDialCodeToCountryData() should return cached data on subsequent calls")
	}
}

// TestGetDialCodeToCountryData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetDialCodeToCountryData_NotEmpty(t *testing.T) {
	data, err := GetDialCodeToCountryData()
	if err != nil {
		t.Fatalf("GetDialCodeToCountryData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
