// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v6.33.0
// source: dial_code_to_country.proto

package dial_code_to_country

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DialCodeToCountryData maps dial codes to country codes.
// Data files: data.json
type DialCodeToCountryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialCodeToCountry map[string]*CountryCodes `protobuf:"bytes,1,rep,name=dial_code_to_country,json=dialCodeToCountry,proto3" json:"dial_code_to_country,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DialCodeToCountryData) Reset() {
	*x = DialCodeToCountryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dial_code_to_country_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialCodeToCountryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialCodeToCountryData) ProtoMessage() {}

func (x *DialCodeToCountryData) ProtoReflect() protoreflect.Message {
	mi := &file_dial_code_to_country_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialCodeToCountryData.ProtoReflect.Descriptor instead.
func (*DialCodeToCountryData) Descriptor() ([]byte, []int) {
	return file_dial_code_to_country_proto_rawDescGZIP(), []int{0}
}

func (x *DialCodeToCountryData) GetDialCodeToCountry() map[string]*CountryCodes {
	if x != nil {
		return x.DialCodeToCountry
	}
	return nil
}

// CountryCodes contains a list of country codes for a dial code.
type CountryCodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *CountryCodes) Reset() {
	*x = CountryCodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dial_code_to_country_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountryCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryCodes) ProtoMessage() {}

func (x *CountryCodes) ProtoReflect() protoreflect.Message {
	mi := &file_dial_code_to_country_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryCodes.ProtoReflect.Descriptor instead.
func (*CountryCodes) Descriptor() ([]byte, []int) {
	return file_dial_code_to_country_proto_rawDescGZIP(), []int{1}
}

func (x *CountryCodes) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

var File_dial_code_to_country_proto protoreflect.FileDescriptor

var file_dial_code_to_country_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x69, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x64, 0x69,
	0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x22, 0xf6, 0x01, 0x0a, 0x15, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x54,
	0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x73, 0x0a, 0x14,
	0x64, 0x69, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x64, 0x69, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x54, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x11,
	0x64, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x1a, 0x68, 0x0a, 0x16, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64,
	0x69, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x24, 0x0a, 0x0c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dial_code_to_country_proto_rawDescOnce sync.Once
	file_dial_code_to_country_proto_rawDescData = file_dial_code_to_country_proto_rawDesc
)

func file_dial_code_to_country_proto_rawDescGZIP() []byte {
	file_dial_code_to_country_proto_rawDescOnce.Do(func() {
		file_dial_code_to_country_proto_rawDescData = protoimpl.X.CompressGZIP(file_dial_code_to_country_proto_rawDescData)
	})
	return file_dial_code_to_country_proto_rawDescData
}

var file_dial_code_to_country_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dial_code_to_country_proto_goTypes = []interface{}{
	(*DialCodeToCountryData)(nil), // 0: dial_code_to_country.DialCodeToCountryData
	(*CountryCodes)(nil),          // 1: dial_code_to_country.CountryCodes
	nil,                           // 2: dial_code_to_country.DialCodeToCountryData.DialCodeToCountryEntry
}
var file_dial_code_to_country_proto_depIdxs = []int32{
	2, // 0: dial_code_to_country.DialCodeToCountryData.dial_code_to_country:type_name -> dial_code_to_country.DialCodeToCountryData.DialCodeToCountryEntry
	1, // 1: dial_code_to_country.DialCodeToCountryData.DialCodeToCountryEntry.value:type_name -> dial_code_to_country.CountryCodes
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dial_code_to_country_proto_init() }
func file_dial_code_to_country_proto_init() {
	if File_dial_code_to_country_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dial_code_to_country_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialCodeToCountryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dial_code_to_country_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountryCodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dial_code_to_country_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dial_code_to_country_proto_goTypes,
		DependencyIndexes: file_dial_code_to_country_proto_depIdxs,
		MessageInfos:      file_dial_code_to_country_proto_msgTypes,
	}.Build()
	File_dial_code_to_country_proto = out.File
	file_dial_code_to_country_proto_rawDesc = nil
	file_dial_code_to_country_proto_goTypes = nil
	file_dial_code_to_country_proto_depIdxs = nil
}
