// Code generated by generateGoFromSchema.js. DO NOT EDIT.

package subdivisions

import (
    "embed"
    "encoding/json"
)

// SubdivisionsData represents root structure
type SubdivisionsData struct {
    CountryName string `json:"country_name"`
    States SubdivisionsDataStates `json:"states"`
}

// GetCountryName returns the country_name
func (d *SubdivisionsData) GetCountryName() string {
    return d.CountryName
}

// GetStates returns the states
func (d *SubdivisionsData) GetStates() SubdivisionsDataStates {
    return d.States
}


//go:embed "data/*.json"
var subdivisionsFS embed.FS

// SubdivisionsDataInstance contains the generated data
var SubdivisionsDataInstance SubdivisionsData

func init() {
    data, err := subdivisionsFS.ReadFile("data/data.json")
    if err != nil {
        panic(err)
    }

    if err := json.Unmarshal(data, &SubdivisionsDataInstance); err != nil {
        panic(err)
    }
}

// GetSubdivisionsData returns the instance of SubdivisionsData
func GetSubdivisionsData() *SubdivisionsData {
    return &SubdivisionsDataInstance
}