// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity_entity_types

import (
	_ "embed"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
)

//go:embed data/data.json
var dataJSON []byte

var (
	data     *EntityTypesData
	dataOnce sync.Once
	dataErr  error
)

// GetEntityTypesData retrieves the data.
func GetEntityTypesData() (*EntityTypesData, error) {
	dataOnce.Do(func() {
		data = &EntityTypesData{}
		unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
		dataErr = unmarshaler.Unmarshal(dataJSON, data)
	})
	return data, dataErr
}
