// Code generated by i18nify go generator. DO NOT EDIT.

package business_entity_entity_types

import (
	"testing"
)

// TestGetEntityTypesData tests that the data can be loaded successfully.
// This ensures the JSON data is valid and matches the proto schema.
func TestGetEntityTypesData(t *testing.T) {
	data, err := GetEntityTypesData()
	if err != nil {
		t.Fatalf("GetEntityTypesData() error = %v", err)
	}

	if data == nil {
		t.Fatal("GetEntityTypesData() returned nil data")
	}

	t.Log("Data loaded successfully")
}

// TestGetEntityTypesData_Idempotent tests that multiple calls return
// the same cached instance.
func TestGetEntityTypesData_Idempotent(t *testing.T) {
	// Call twice to verify caching works
	data1, err1 := GetEntityTypesData()
	if err1 != nil {
		t.Fatalf("First GetEntityTypesData() error = %v", err1)
	}

	data2, err2 := GetEntityTypesData()
	if err2 != nil {
		t.Fatalf("Second GetEntityTypesData() error = %v", err2)
	}

	// Should return the same pointer (cached)
	if data1 != data2 {
		t.Error("GetEntityTypesData() should return cached data on subsequent calls")
	}
}

// TestGetEntityTypesData_NotEmpty performs a basic sanity check
// that the loaded data is not empty.
func TestGetEntityTypesData_NotEmpty(t *testing.T) {
	data, err := GetEntityTypesData()
	if err != nil {
		t.Fatalf("GetEntityTypesData() error = %v", err)
	}

	// Use reflection or proto methods to check if data has any fields set
	// This is a basic check - specific packages may want more detailed validation
	if data == nil {
		t.Error("Data should not be nil")
	}
}
