name: (i18nify-js) Build & Validate
on:
  pull_request:

defaults:
  run:
    working-directory: packages/i18nify-js

jobs:
  # JOB to run change detection
  check-if-i18nify-js:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.filter.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'packages/i18nify-js/**'

  validate:
    name: Validate Source code
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    if: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      - name: Install dependencies
        run: yarn
      - name: run eslint
        run: yarn lint
      - name: run tsc
        run: yarn tsc

  build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    if: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      - name: Install dependencies
        run: yarn
      - name: run build
        run: yarn build
