name: (i18nify-js) Build & Validate

on:
  pull_request:

jobs:
  validate:
    name: Validate Source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute steps if 'packages/i18nify-js' folder was changed
        uses: ./.github/actions/execute-if-i18nify-js
        with:
          steps: test-test
