# Danger: automating your team's conventions surrounding code review
# More info in Readme
name: Danger CI

on:
  pull_request:
    branches:
      - master
    types:
      [
        opened,
        edited,
        reopened,
        synchronize,
        labeled,
        unlabeled,
        review_requested,
        review_request_removed,
      ]
    paths:
      - 'packages/i18nify-js/**'

jobs:
  build-base:
    name: Generate Base Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Use Node v20
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      - name: Install Dependencies
        run: yarn
      - name: Make Build
        run: yarn build-js
      - name: Upload base stats
        uses: actions/upload-artifact@v3
        with:
          name: base
          path: |
            ./packages/i18nify-js/lib
            !./packages/i18nify-js/lib/**/*.map
          retention-days: 1

  build-pr:
    name: Generate PR Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - name: Use Node v20
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      - name: Install Dependencies
        run: yarn
      - name: Make Build
        run: yarn build-js
      - name: Upload pr build
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: |
            ./packages/i18nify-js/lib
            !./packages/i18nify-js/lib/**/*.map
          retention-days: 1

  Danger:
    name: Run Danger JS
    runs-on: ubuntu-latest
    needs: [build-base, build-pr]
    env:
      # As Danger uses a bot to put comments on your pr you need to
      # use `secrets.CI_BOT_TOKEN` (Personal Access Token) to provide write access to bot.
      DANGER_GITHUB_API_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      DANGER_DISABLE_TRANSPILATION: 'true'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Download stats
        uses: actions/download-artifact@v3
        with:
          path: ./build

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build

      - name: Danger
        uses: danger/danger-js@11.2.6
