name: (i18nify-js) Build & Validate
on:
  pull_request:

jobs:
  # JOB to run change detection
  check-if-i18nify-js:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.filter.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'packages/i18nify-js/**'

  validate:
    name: Validate Source code
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - name: Skip validation (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected, skipping validation"
      
      - name: Setup and validate
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v3
      
      - name: Setup Node
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      
      - name: Install dependencies and run validation
        if: env.SHOULD_RUN == 'true'
        working-directory: packages/i18nify-js
        run: |
          yarn
          yarn lint
          yarn tsc

  build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - name: Skip build (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected, skipping build"
      
      - name: Setup for build
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v3
      
      - name: Setup Node
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      
      - name: Install dependencies and build
        if: env.SHOULD_RUN == 'true'
        working-directory: packages/i18nify-js
        run: |
          yarn
          yarn build
