# Danger: automating your team's conventions surrounding code review
# More info in Readme
name: Danger CI

on:
  pull_request:
    branches:
      - master
    types:
      [
        opened,
        edited,
        reopened,
        synchronize,
        labeled,
        unlabeled,
        review_requested,
        review_request_removed,
      ]

jobs:
  # JOB to run change detection
  check-if-i18nify-js:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.filter.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'packages/i18nify-js/**'

  build-base:
    name: Generate Base Build
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - name: Skip base build (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected, skipping base build"
      
      - name: Checkout base ref
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      
      - name: Setup Node and build
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      
      - name: Install dependencies and build
        if: env.SHOULD_RUN == 'true'
        run: |
          yarn
          yarn build-js
      
      - name: Upload base stats
        if: env.SHOULD_RUN == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: base
          path: |
            ./packages/i18nify-js/lib
            !./packages/i18nify-js/lib/**/*.map
          retention-days: 1

  build-pr:
    name: Generate PR Build
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - name: Skip PR build (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected, skipping PR build"
      
      - name: Checkout PR code
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v3
      
      - name: Setup Node and build
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      
      - name: Install dependencies and build
        if: env.SHOULD_RUN == 'true'
        run: |
          yarn
          yarn build-js
      
      - name: Upload PR build
        if: env.SHOULD_RUN == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: |
            ./packages/i18nify-js/lib
            !./packages/i18nify-js/lib/**/*.map
          retention-days: 1

  Danger:
    name: Run Danger JS
    runs-on: ubuntu-latest
    needs: [build-base, build-pr, check-if-i18nify-js]
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
      # As Danger uses a bot to put comments on your pr you need to
      # use `secrets.CI_BOT_TOKEN` (Personal Access Token) to provide write access to bot.
      DANGER_GITHUB_API_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      DANGER_DISABLE_TRANSPILATION: 'true'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Skip Danger (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected, skipping Danger analysis"

      - name: Checkout and setup
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v3

      - name: Setup Node
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Download and analyze artifacts
        if: env.SHOULD_RUN == 'true'
        uses: actions/download-artifact@v4
        with:
          path: ./build

      - name: Display structure and run Danger
        if: env.SHOULD_RUN == 'true'
        run: |
          ls -R ./build
        working-directory: ./

      - name: Run Danger analysis
        if: env.SHOULD_RUN == 'true'
        uses: danger/danger-js@11.2.6
