name: (i18nify-js) CodeCov Code Coverage PR Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # JOB to run change detection
  check-if-i18nify-js:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'packages/i18nify-js/**'

  coverage:
    name: CodeCov analysis on coverage
    runs-on: ubuntu-latest
    needs: check-if-i18nify-js
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' && !(github.head_ref == 'changeset-release/master' && github.actor == 'rzpcibot') && !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Skip coverage (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected or CI skipped, skipping coverage analysis"
      
      - name: Checkout Codebase
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v3
      
      - name: Setup Node v20
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.1
      
      - name: Setup Cache & Install Dependencies
        if: env.SHOULD_RUN == 'true'
        uses: bahmutov/npm-install@v1.10.9
        with:
          install-command: yarn --frozen-lockfile
      
      - name: Run Tests and Upload Coverage
        if: env.SHOULD_RUN == 'true'
        working-directory: packages/i18nify-js
        run: yarn test
      
      - name: Upload coverage to Codecov
        if: env.SHOULD_RUN == 'true'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          verbose: true
      
      - name: Upload Unit Test Results
        if: env.SHOULD_RUN == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: src/coverage/**/*.xml

  publish-test-results:
    name: 'Publish Unit Tests Results'
    needs: [coverage, check-if-i18nify-js]
    runs-on: ubuntu-latest
    if: success() || failure()
    env:
      SHOULD_RUN: ${{ needs.check-if-i18nify-js.outputs.modified == 'true' }}
    steps:
      - name: Skip publishing (no changes)
        if: env.SHOULD_RUN != 'true'
        run: echo "No i18nify-js changes detected, skipping test results publishing"
      
      - name: Download and publish test results
        if: env.SHOULD_RUN == 'true'
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Unit Test Results
        if: env.SHOULD_RUN == 'true'
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.6
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/**/*.xml
