name: (i18nify-js) Build & Validate

on:
  pull_request:

jobs:
  validate:
    name: Validate Source code
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'packages/i18nify-js/**'

      # Run only if some file in 'src' folder was changed
      - name: Execute if 'src' folder was changed
        if: steps.changes.outputs.src == 'true'
        run: |
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20.3.1
            - name: Install dependencies
              run: yarn
            - name: Run eslint
              run: yarn lint
            - name: Run tsc
              run: yarn tsc
          working-directory: packages/i18nify-js

      # If 'src' folder wasn't changed, pass the action
      - name: Skip if 'src' folder was not changed
        if: steps.changes.outputs.src == 'false'
        run: echo "No changes in 'src' folder, skipping validation"

  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
      - name: Install dependencies
        run: yarn
      - name: run build
        run: yarn build
        working-directory: packages/i18nify-js
