name: i18nify Unpublish

on:
  workflow_dispatch:
  push:

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  unpublish:
    name: Unpublish
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.1
      - name: Install dependencies
        run: yarn
      - name: Publish to public npm registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: yarn publish-npm
